version: "3"
services:
  api:
    build: .
    container_name: school-website-api
    entrypoint: ./docker-entrypoint.sh
    environment:
      - NODE_ENV=development
      - DB_RESET=true
      - DB_MIGRATE=true
      - DB_SEED=true
      - TYPE=dev
    ports:
      - "4500:4500"
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
  postgres:
    image: postgres:alpine
    restart: always
    container_name: school-website-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school_website
